### ISSUE TITLE
How to use this

### ISSUE THREAD

**Issue by SamJongenelen** [toverainc/willow-autocorrect#1]
Hey, this looks like an amazing addition! 
How would one use this, when using only a WAS docker image?
I see a 'WAS Command' checkbox in WAS settings?

**Comment by kristiankielhofner** [comment]
Thanks!

We just created a new Discord channel for experimental features. The first topic of discussion is WAC and if you'd like to [join us there](https://discord.com/channels/1161666824178503720/1185238467265970288) we can have much more interactive discussions for questions like this.

Hope to see you there!

**Comment by SamJongenelen** [comment]
For future reference: this option will be included in future version of WAS
